name: API Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Verify Newman and Node versions
        run: |
              newman --version
              node --version
      - name: Install HTML Extra Reporter for Newman
        run: sudo npm install -g newman-reporter-htmlextra
        
      - name: Run Postman Collection
        run: newman run test_api_collection.json -g test_env.json --delay-request 1 --reporters cli,htmlextra --reporter-htmlextra-export ./output/Report.html
     
      - name: Upload Report Artifacts
        uses: actions/upload-artifact@v4
        with:
              name: test-report
              path: ./output/Report.html
